project:
  title: "LEVANTE"
  type: datapage

website:
  navbar:
    logo: ""

format:
  datapage-html:
    theme: [resources/scss/theme.scss, resources/scss/layout.scss]
    mainfont: whitney-book, system-ui, sans-serif
    callout-icon: false

execute: 
  echo: false
  message: false
  warning: false
  error: false

# mode: local
# mode: cache
redivis:
  user: levante
  dataset: levante-data-pilots-processed
  # dataset: pilot-western-ca-main-processed
  table: scores

resources:
  - "resources/fonts/*"
